name: DTools3
version: '1.1.3-SNAPSHOT'
main: com.francobm.dtools3.DTools3
api-version: '1.16'
commands:
  dtools3:
    description: DTools3 commands
    usage: /<command>
    aliases: [dtools, dt, dt3]
  soul:
    description: See the soul of the player
    usage: /<command>
    aliases: [alma]
  lives:
    description: See the lives of the player
    usage: /<command>
    aliases: [vidas]
softdepend:
  - PlaceholderAPI
  - StreamEvents
  - ModelEngine
  - BetterRevive
  - Multiverse-Core